version: '3.4'

networks:
  deploy-guide-dev:
    driver: bridge

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 7104:80
      - 5178:443
    networks:
      - deploy-guide-dev
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 4200:4200
    networks:
      - deploy-guide-dev

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: Refugio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - deploy-guide-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
